# Profil OPTIONNEL pour lancer l'appli sur SQL Server (comme dans le projet Poudlard).
# Activation : -Dspring.profiles.active=mssql  (ou dans la Run Configuration IntelliJ)
spring.datasource.url=jdbc:sqlserver://localhost:1433;database=PokemonM2;encrypt=false
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=Soleil123
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never
spring.h2.console.enabled=false
